---
title: "Papers and works"
---


## Software

- Maxime Jaunatre, Julien Barrere, Thomas Cordonnier, Arnaud Guyennon, Bjoern Reineking, et al.. matreex: Simulation IPM for forest dynamic depending on climatic variables from Kunstler et al (2020). 2022, [[https://hal.science/hal-04453769]](https://hal.science/hal-04453769)

### Publications

-  Barrere, J., Reineking, B., Jaunatre, M., & Kunstler, G. (2024). Forest storm resilience depends on the interplay between functional composition and climate—Insights from European-scale simulations. Functional Ecology, 00, 1–17. [[Open access]](https://doi.org/10.1111/1365-2435.14489)

-  E. Barthelemy, M. Jaunatre, and F. Munoz. “ecophylo: Simulating and assessing eco-evolutionary dynamics under past environmental changes in Python and R”. in: Global Ecology and Biogeography [in review].

-  Elizabeth Barthelemy et al. “Imprints of Past Habitat Area Reduction on Extant Taxonomic, Functional, and Phylogenetic Composition”. In: Frontiers in Ecology and Evolution 9 (2021). [[Open access]](https://www.frontiersin.org/articles/10.3389/fevo.2021.634413/full)

### Reports

- Merzereaud Mathieu, Macher Claire, Bertignac Michel, Fresard Marjolaine, Guyader Olivier, Le Grand Christelle, Gourguet Sophie, Briton Florence, Jaunatre Maxime (2022). IAM: Impact Assessment Model for fisheries management. Notice. https://archimer.ifremer.fr/doc/00784/89579/

- M. Jaunatre "Evolutionary and ecological process acting on rich community assemblage." Master 2 report (2020). [[Pdf]](https://gowachin.github.io/Stage_M2_JAUNATRE.pdf)